services:
  frontend:
    build:
      context: ./front-cmpc-libros
      dockerfile: Dockerfile
    container_name: front-cmpc-libros
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000/api
    networks:
      - cmpc-net

  backend:
    image: cmpc-libros-backend # Cambia esto por el nombre real de tu imagen backend
    container_name: cmpc-libros-backend
    build:
      context: ./cmpc-libros # Ajusta la ruta al backend si es necesario
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=cmpclibrarydb
      - JWT_SECRET=supersecret123
    depends_on:
      - db
    networks:
      - cmpc-net

  db:
    image: postgres:15-alpine
    container_name: cmpc-libros-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cmpclibrarydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cmpc-net

volumes:
  db_data:

networks:
  cmpc-net:
    driver: bridge
